### ISSUE TITLE
Dataset statistics and missing images

### ISSUE THREAD

**Issue by manisoftwartist** [tjubiit/TJU-DHD#8]
There are duplicate images in the dataset.  Example `dhd_campus/images/train/000000016083.jpg` and `dhd_campus/images/test/000000051853.jpg` are the same image.

Total number of images (no duplicates) = **105076**

Combining both campus and traffic datasets, I have the following statistics:

|Class label| #Instances|
| :---: |:---: |
Car       |    152860|
Cyclist   |     76765|
Pedestrian  |  349743|
Truck   |       16634|
Van      |      29877|

|Type|#instances|
| :---: |:---: |
campus train| 291688
campus val|47713
traffic train|251691
traffic val|34787

Total number of bounding boxes = **625879** 

### Missing images
The following 3 image paths are present in the annotation files but the images seem to be missing in your dataset.
dhd_campus/images/train/1499435044634.jpg
dhd_campus/images/train/1497315953923.jpg
dhd_campus/images/train/1497405070612.jpg

We are running some experiments. We would be grateful if you can check these numbers from your end?

P.S
In `dhd_campus_train.json` ,you have `pedstrian` as a label . In `dhd_traffic_train.json`, you have `Car`, `Van` and `Pedestrian`  
I renamed `pedstrian` to `Pedestrian`.

**Comment by Hanqing-Sun** [comment]
Thank you for your interest in our dataset. We did some investigations and apologize for the late reply.
1. The duplication is confirmed using md5sum. 500+ dups are found and one of them is cross-split. We suppose that won't impact the training and benchmarking too much, please let us know if you observe significant performance issues.
2. The number of images reported in the paper is 115,354 (traffic 60,266 + campus 55,088, Tab. I). Discarding all the dups won't decrease it to the commented 105,076. Do we share an identical stat dimension or did we miss anything?
3. We find the files in the dhd-traffic annotation instead of that in the dhd-campus, therefore, the path should be `dhd_traffic/images/train/1499435044634.jpg`. The md5s of all files are provided in the [README.md](https://github.com/tjubiit/TJU-DHD/blob/master/README.md), you can have a check of the downloaded zips.
4. The `pedstrian` is a typo, we will fix it later.
